config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'my_friendlist', to: 'users#my_friendlist'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord

    has_many :user_stocks
    has_many :user, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.new_lookup(ticker_symbol)
        # use self so that you can use it without create a new instance
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
            endpoint: 'https://sandbox.iexapis.com/v1')
        begin
            return new(ticker: ticker_symbol, 
                  name: client.company(ticker_symbol).company_name, 
                  last_price: client.price(ticker_symbol))
        rescue => exception
            return nil
        end
        # because this is within the Stock model, we don't have to use Stock.new
    end

    def self.check_db(ticker_symbol)
        where(ticker:ticker_symbol).first
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end
  
  def friend_already_tracked?(user)
    user = User.check_db(user)
    return false unless user
    friends.where(id: user.id).exists?
  end


  def under_stock_limit?
    stocks.count < 10
  end

  def under_friend_limit?
    friends.count < 10
  end
  
  def can_track_stock?(ticker_symbol)
   under_stock_limit? && !stock_already_tracked?(ticker_symbol)
   
  end
  def can_follow_friend?(user)
    return true
    #under_friend_limit? && !friend_already_tracked?(user)
    
  end

  def full_name 
    return "#{first_name}  #{last_name}" if (first_name? || last_name?)
    "User"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end
  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id}
  end

  def not_friend_with? (friend_id)
    !self.friends.where(id: friend_id).exists?
  end

  
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name])
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend_id])
    @friendship = Friendship.create(user: current_user, friend_id: params[:friend_id])
    # current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "You follows #{friend.full_name } "
    else
      flash[:alert] = "something goes wrong "
    end
    
    redirect_to my_friendlist_path
  end

  def destroy
    friend = User.find(params[:id])
    friendship = current_user.friendships.where( friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "You unfollowed #{friend.full_name } "
    redirect_to my_friendlist_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        if params[:stock].present?
            @stock = Stock.new_lookup(params[:stock])
            if @stock
                respond_to do |format|
                    format.js { render partial: 'users/result'}
                end
            else
                respond_to do |format|
                    flash.now[:alert] = "Please enter a valid symbol"
                    format.js { render partial: 'users/result'}
                end
                
        
            end
        else
            respond_to do |format|
                flash.now[:alert] = "Please enter a symbol to search"
                format.js { render partial: 'users/result'}
            end
            

        end
    end
  end
  

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
            stock = Stock.new_lookup(params[:ticker])
            stock.save
        end
        @user_stock = UserStock.create(user: current_user, stock: stock)
        flash[:notice] = "Stock #{stock.name} was added to your watchlist"
        redirect_to my_portfolio_path
    end

    def destroy
        stock = Stock.find(params[:id])
        user_stock = UserStock.where(user_id: current_user.id, stock: stock).first
        user_stock.destroy
        flash[:notice] = "You unfollowed #{stock.ticker}!"
        redirect_to my_portfolio_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

  def my_friendlist
    @friends = current_user.friends
  end 
  
  def show
    @user = User.find(params[:id])
  end

  def search
    if params[:user].present?
      @query_friends = User.search(params[:user])
      @query_friends = current_user.except_current_user(@query_friends)
      if @query_friends
          respond_to do |format|
              format.js { render partial: 'users/friend_result'}
          end
      else
          respond_to do |format|
              flash.now[:alert] = "Cannot find user that match #{params[:user]}"
              format.js { render partial: 'users/friend_result'}
          end
        end
    else
        respond_to do |format|
            flash.now[:alert] = "Please enter a valid name or email"
            format.js { render partial: 'users/friend_result'}
        end
        

    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <%= link_to 'WeiStock', root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if request.path == root_path %>"> 
          <%= link_to 'Home<span class="sr-only">(current)</span>'.html_safe, root_path, class:'nav-link'%>
        </li>
        <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
          <%= link_to 'My portfolio', my_portfolio_path, class:'nav-link' %>
        </li>
        <li class="nav-item <%= 'active' if request.path == my_friendlist_path %>">
          <%= link_to 'My Friends', my_friendlist_path, class:'nav-link' %>
        </li>
        <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit Profile', edit_user_registration_path , class:'dropdown-item' %>
            <%= link_to( 'Log out', destroy_user_session_path,class:'dropdown-item', method: :delete) %>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <% else %>
          <li class="nav-item">
          <%= link_to 'Login', new_user_session_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class:'nav-link' %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav mr-2">
        <li class="nav-item">
         Hi! <%= current_user.full_name if current_user.present? %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if name == 'notice' %>
        <div class="flash-msg alert alert-success mt-3">
            <%= msg %>
        </div>
    <% elsif name =='alert' %>
        <div class="flash-msg alert alert-danger mt-3">
            <%= msg %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeiStock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container mt-4">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<h6>My Tracked Stocks</h6>
<% if !@tracked_stocks.empty? %>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Ticker</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  
    <% @tracked_stocks.each do |stock|  %>
    <tr>
      <th scope="row"><%= stock.ticker %></th>
      <td><%= stock.name %></td>
      <td><%= stock.last_price %></td>
      <td><%= link_to 'unfollow', user_stock_path(stock), method: :delete, data:{confirm: 'Are you sure?'}, class:'btn btn-sm btn-outline-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/users/_friend_result.html.erb
<% if @query_friends %>
<div class="card card-header d-flex flex-column ">
    <% @query_friends.each do |friend| %>
        <div class="d-flex flex-row justify-content-between py-1">
            <div>
                <%= link_to friend.full_name, user_path(friend) %> -
                <%= friend.email %>
            </div>
        
        <% if current_user.not_friend_with?(friend) %>
            <%= link_to 'Follow', friendships_path(user: current_user, friend_id: friend.id), method: :post, class:'btn btn-outline-primary btn-sm'%>
        <% else %>
            <div class="btn btn-disable btn-sm text-muted">following</div>
        <% end %>
        </div>
    <% end %> 
</div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#result').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_list.html.erb
<h6>My Tracked People</h6>
<% if !@friends.empty? %>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Name</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  
    <% @friends.each do |user|  %>
    <tr>
      <td scope="row"><%= link_to user.email, user_path(user) %></td>
      <td><%= user.full_name %></td>
      <td><%= link_to 'unfollow', friendship_path(user), method: :delete, data:{confirm: 'Are you sure?'}, class:'btn btn-sm btn-outline-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/users/_result.html.erb
<% if @stock %>
<div class="card card-header d-flex flex-row justify-content-between">
    <div>
        <%= @stock.ticker %> -
        <%= @stock.name %> -
        $<%= @stock.last_price %>
    </div>
    
    <% if current_user.can_track_stock?(@stock.ticker) %>
        <%= link_to 'Follow', user_stocks_path(user: current_user, ticker: @stock.ticker), class:'btn btn-outline-primary btn-sm', method: :post %>
    <% else %>
        <% if !current_user.under_stock_limit? %>
            <div class="btn btn-disable btn-sm text-muted">10 stocks</div>
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>
            <div class="btn btn-disable btn-sm text-muted">following</div>
        <% end %>
    <% end %>
</div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#result').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/my_friendlist.html.erb
<h3>My Friend List</h3>
<h5>Search friends</h5>
<%= form_tag( search_friend_path, remote: true, method: :get) do %>
<div class="form-group row">
    <div class="col-sm-9 pr-0">
        <%= text_field_tag :user, params[:user], placeholder: "name or email", autofocus: true, class:'form-control form-control-large' %>
    </div>
    <div class="col-sm-3">
        <%= button_tag type: :submit, class: 'btn btn-primary btn-large' do%>
        <%= fa_icon 'search', text: "Search" %>
        <% end %>
    </div>
</div>
<% end %>

<div id="result">
    <%= render 'users/friend_result' %>
</div>

<hr>
<%= render'list' %>

app/views/users/my_portfolio.html.erb
<h3>My Portfolio</h3>
<hr>
<h5>Search Stocks</h5>
<%= form_tag( search_stock_path, remote: true, method: :get) do %>
<div class="form-group row">
    <div class="col-sm-9 pr-0">
        <%= text_field_tag :stock, params[:stock], placeholder: "stock ticker symbol", autofocus: true, class:'form-control form-control-large' %>
    </div>
    <div class="col-sm-3">
        <%= button_tag type: :submit, class: 'btn btn-primary btn-large' do%>
        <%= fa_icon 'search', text: "Search" %>
        <% end %>
    </div>
</div>
<% end %>

<div id="result">
    <%= render 'users/result' %>
</div>

<hr>

<%= render'stocks/list' %>

app/views/users/show.html.erb
<h3><%= @user.full_name %></h3>
<hr>
<table>
  <tr>
    <td scope="row"><%= link_to user.email, user_path(user) %></td>
    <td><%= link_to 'unfollow', friendship_path(user), method: :delete, data:{confirm: 'Are you sure?'}, class:'btn btn-sm btn-outline-primary' %></td>
  </tr>
</table>

<%= render'stocks/list' %>

app/views/welcome/index.html.erb
<p>Welcome</p>
<%= link_to 'sign out', destroy_user_session_path, method: :delete %>